name: Build Windows EXE and Release

on:
  push:
    tags:
      - 'v*'  # 当你推送 v1.0.0 这类标签时自动触发构建和发布

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --name "YT-DLP Downloader" --onefile --windowed ^
        --add-data "translations;translations" ^
        --add-data "icons;icons" ^
        --icon="appicon.ico" main.py
      shell: cmd

    - name: Rename EXE for Release
      run: ren "dist\YT-DLP Downloader.exe" "yt-dlp-downloader-win.exe"

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: yt-dlp-downloader-win.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
